### ISSUE TITLE
Update for more highlight syntax.

### ISSUE THREAD

**Issue by iKenshu** [thatal/Monokai-Dark#1]
Hey man, I recently tried this one and should be nice if this has the exact same colors highlight for some syntax like self inside python functions or this in javascript functions just like the Monokai Default.

**Comment by thatal** [comment]
Hey man thanks. Will surely work on that.

**Comment by thatal** [comment]
Syntax Color are corrected.

![python syntax](https://user-images.githubusercontent.com/17490342/33252401-0516cd28-d364-11e7-8f2f-58e7468a523b.JPG)

**Comment by iKenshu** [comment]
Perfect!

Thanks man
